//! Generate Dart gRPC client code from a service definition.
//!
//! Produces a Dart `XxxClient` class that extends `grpc.Client` with
//! one method per RPC. Uses FlatBuffers for serialization.

use crate::ir::{MethodDef, ServiceDef};
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::fmt::Write as FmtWrite;

/// Generate Dart client code for a service definition.
///
/// Produces a Dart `XxxClient` class with one async method per RPC.
/// The client uses FlatBuffers for serialization and the `package:grpc` library.
pub fn generate(service: &ServiceDef, proto_path: &str) -> String {
    let errors = service.validate();
    if !errors.is_empty() {
        panic!(
            "invalid ServiceDef for client codegen: {}",
            errors.join("; ")
        );
    }

    let mut output = String::new();

    // File header
    writeln!(
        &mut output,
        "// automatically generated by grpc-codegen, do not modify."
    )
    .unwrap();
    writeln!(
        &mut output,
        "// ignore_for_file: unused_import, unused_field, unused_local_variable"
    )
    .unwrap();
    writeln!(&mut output).unwrap();
    writeln!(&mut output, "library;").unwrap();
    writeln!(&mut output).unwrap();

    // Service-level doc comments
    for comment in &service.comments {
        writeln!(&mut output, "/// {comment}").unwrap();
    }

    // Imports
    writeln!(&mut output, "import 'dart:typed_data' show Uint8List;").unwrap();
    writeln!(&mut output, "import 'package:grpc/grpc.dart' as grpc;").unwrap();
    writeln!(
        &mut output,
        "import 'package:flat_buffers/flat_buffers.dart' as fb;"
    )
    .unwrap();

    // Import the generated FlatBuffers types
    // service.package uses dots (e.g., "rterm_rterm.protocol") but Dart imports
    // use slashes (e.g., "rterm_rterm/protocol_generated.dart")
    let package_import = if service.package.is_empty() {
        format!("{proto_path}_generated.dart")
    } else {
        let package_path = service.package.replace('.', "/");
        format!("package:{}/{}_generated.dart", proto_path, package_path)
    };
    writeln!(&mut output, "import '{package_import}';").unwrap();
    writeln!(&mut output).unwrap();

    // Client class
    let client_name = format!("{}Client", service.name.to_upper_camel_case());

    writeln!(&mut output, "class {client_name} extends grpc.Client {{").unwrap();
    writeln!(
        &mut output,
        "  {client_name}(grpc.ClientChannel channel, {{"
    )
    .unwrap();
    writeln!(&mut output, "    grpc.CallOptions? options,").unwrap();
    writeln!(
        &mut output,
        "    List<grpc.ClientInterceptor>? interceptors,"
    )
    .unwrap();
    writeln!(
        &mut output,
        "  }}) : super(channel, options: options, interceptors: interceptors);"
    )
    .unwrap();
    writeln!(&mut output).unwrap();

    // Factory method to create a client with a managed channel
    writeln!(&mut output, "  static Future<{client_name}> create({{").unwrap();
    writeln!(&mut output, "    required String host,").unwrap();
    writeln!(&mut output, "    required int port,").unwrap();
    writeln!(&mut output, "    grpc.CallOptions? options,").unwrap();
    writeln!(
        &mut output,
        "    List<grpc.ClientInterceptor>? interceptors,"
    )
    .unwrap();
    writeln!(&mut output, "  }}) async {{").unwrap();
    writeln!(&mut output, "    final channel = grpc.ClientChannel(").unwrap();
    writeln!(&mut output, "      host,").unwrap();
    writeln!(&mut output, "      port: port,").unwrap();
    writeln!(&mut output, "      options: grpc.ChannelOptions(").unwrap();
    writeln!(
        &mut output,
        "        credentials: grpc.ChannelCredentials.insecure(),"
    )
    .unwrap();
    writeln!(&mut output, "      ),").unwrap();
    writeln!(&mut output, "    );").unwrap();
    writeln!(
        &mut output,
        "    return {client_name}(channel, options: options, interceptors: interceptors);"
    )
    .unwrap();
    writeln!(&mut output, "  }}").unwrap();
    writeln!(&mut output).unwrap();

    // Collect all types needed for serialization helpers
    let mut types: Vec<String> = Vec::new();

    // Generate methods and ClientMethod descriptors
    for method in &service.methods {
        gen_dart_method(&mut output, method, &service.fully_qualified_name());
        // Use short names for serialization helper function names
        let input = extract_short_name(&method.input_type);
        let output_type = extract_short_name(&method.output_type);
        if !types.contains(&input) {
            types.push(input);
        }
        if !types.contains(&output_type) {
            types.push(output_type);
        }
        writeln!(&mut output).unwrap();
    }

    // Generate serialization helpers
    gen_serializers(&mut output, &types);

    writeln!(&mut output).unwrap();
    writeln!(&mut output, "}}").unwrap();

    output
}

fn gen_dart_method(mut output: &mut String, method: &MethodDef, service_fqn: &str) {
    let method_name_snake = method.name.to_snake_case();
    let grpc_path = method.grpc_path(service_fqn);

    // Method doc comments
    for comment in &method.comments {
        writeln!(output, "  /// {comment}").unwrap();
    }

    // Input/output types - use qualified names for Dart type annotations
    let input_type = extract_type_name(&method.input_type);
    let output_type = extract_type_name(&method.output_type);
    // Use short names for serialization helper function references
    let input_type_short = extract_short_name(&method.input_type);
    let output_type_short = extract_short_name(&method.output_type);

    // Generate the ClientMethod descriptor
    writeln!(
        &mut output,
        "  static final _{method_name_snake} = grpc.ClientMethod<{input_type}, {output_type}>("
    )
    .unwrap();
    writeln!(&mut output, "    '{grpc_path}',").unwrap();
    writeln!(&mut output, "    _serialize_{input_type_short},").unwrap();
    writeln!(&mut output, "    _deserialize_{output_type_short},").unwrap();
    writeln!(&mut output, "  );").unwrap();
    writeln!(output).unwrap();

    // Generate the method
    match (method.client_streaming, method.server_streaming) {
        (false, false) => {
            // Unary RPC
            gen_unary_method(output, &input_type, &output_type, &method_name_snake);
        }
        (false, true) => {
            // Server streaming
            gen_server_streaming_method(output, &input_type, &output_type, &method_name_snake);
        }
        (true, false) => {
            // Client streaming
            gen_client_streaming_method(output, &input_type, &output_type, &method_name_snake);
        }
        (true, true) => {
            // Bidirectional streaming
            gen_bidi_streaming_method(output, &input_type, &output_type, &method_name_snake);
        }
    }
}

fn gen_unary_method(
    output: &mut String,
    input_type: &str,
    output_type: &str,
    method_name_snake: &str,
) {
    writeln!(output, "  Future<{output_type}> {method_name_snake}(").unwrap();
    writeln!(output, "    {input_type} request, {{").unwrap();
    writeln!(output, "    grpc.CallOptions? options,").unwrap();
    writeln!(output, "  }}) async {{").unwrap();
    writeln!(output, "    final response = await runUnary(").unwrap();
    writeln!(output, "      _{method_name_snake},").unwrap();
    writeln!(output, "      request,").unwrap();
    writeln!(output, "      options: options,").unwrap();
    writeln!(output, "    );").unwrap();
    writeln!(output, "    return response;").unwrap();
    writeln!(output, "  }}").unwrap();
}

fn gen_server_streaming_method(
    output: &mut String,
    input_type: &str,
    output_type: &str,
    method_name_snake: &str,
) {
    writeln!(
        output,
        "  grpc.ResponseStream<{output_type}> {method_name_snake}("
    )
    .unwrap();
    writeln!(output, "    {input_type} request, {{").unwrap();
    writeln!(output, "    grpc.CallOptions? options,").unwrap();
    writeln!(output, "  }}) {{").unwrap();
    writeln!(
        output,
        "    return runServerStreaming(_{method_name_snake}, request, options: options);"
    )
    .unwrap();
    writeln!(output, "  }}").unwrap();
}

fn gen_client_streaming_method(
    output: &mut String,
    input_type: &str,
    output_type: &str,
    method_name_snake: &str,
) {
    writeln!(output, "  Future<{output_type}> {method_name_snake}(").unwrap();
    writeln!(output, "    Stream<{input_type}> request, {{").unwrap();
    writeln!(output, "    grpc.CallOptions? options,").unwrap();
    writeln!(output, "  }}) async {{").unwrap();
    writeln!(
        output,
        "    final response = await runClientStreaming(_{method_name_snake}, request, options: options);"
    )
    .unwrap();
    writeln!(output, "    return response;").unwrap();
    writeln!(output, "  }}").unwrap();
}

fn gen_bidi_streaming_method(
    output: &mut String,
    input_type: &str,
    output_type: &str,
    method_name_snake: &str,
) {
    writeln!(
        output,
        "  grpc.ResponseStream<{output_type}> {method_name_snake}("
    )
    .unwrap();
    writeln!(output, "    Stream<{input_type}> request, {{").unwrap();
    writeln!(output, "    grpc.CallOptions? options,").unwrap();
    writeln!(output, "  }}) {{").unwrap();
    writeln!(
        output,
        "    return runBidirectionalStreaming(_{method_name_snake}, request, options: options);"
    )
    .unwrap();
    writeln!(output, "  }}").unwrap();
}

/// Generate serialization helper functions for a type.
///
/// Uses the FlatBuffers Builder API to serialize/deserialize messages.
/// Serialization leverages the generated table's unpack() and T.pack() methods.
/// Deserialization uses the generated table's constructor that accepts bytes.
fn gen_serializers(output: &mut String, types: &[String]) {
    // Request serializers
    writeln!(output, "  // Serialization helpers").unwrap();
    for type_name in types {
        writeln!(output).unwrap();
        writeln!(
            output,
            "  static Uint8List _serialize_{type_name}({type_name} request) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    // Serialize by unpacking to T class and using T.pack() to build the table."
        )
        .unwrap();
        writeln!(
            output,
            "    final builder = fb.Builder(deduplicateTables: false);"
        )
        .unwrap();
        writeln!(
            output,
            "    builder.finish(request.unpack().pack(builder));"
        )
        .unwrap();
        writeln!(output, "    return builder.buffer;").unwrap();
        writeln!(output, "  }}").unwrap();

        writeln!(output).unwrap();
        writeln!(
            output,
            "  static {type_name} _deserialize_{type_name}(List<int> responseBytes) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    // The generated FlatBuffers table has a constructor that accepts bytes."
        )
        .unwrap();
        writeln!(output, "    return {type_name}(responseBytes is Uint8List ? responseBytes : Uint8List.fromList(responseBytes));").unwrap();
        writeln!(output, "  }}").unwrap();
    }
}

/// Extract the short type name from a fully qualified path (last segment).
/// Used for serialization helper function names where dots are not allowed.
fn extract_short_name(fully_qualified: &str) -> String {
    fully_qualified
        .split("::")
        .last()
        .unwrap_or(fully_qualified)
        .to_string()
}

/// Extract the type name from a fully qualified path, converting to Dart's `.` separator.
/// Used for Dart type annotations where the package separator matters.
fn extract_type_name(fully_qualified: &str) -> String {
    // Convert Rust's "::" separator to Dart's "." separator
    // e.g., "super::HelloRequest" -> "super.HelloRequest"
    fully_qualified.replace("::", ".")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{MethodDef, ServiceDef};

    fn sample_service() -> ServiceDef {
        ServiceDef {
            name: "Greeter".into(),
            package: "helloworld".into(),
            proto_name: "Greeter".into(),
            comments: vec!["A simple greeter service.".to_string()],
            methods: vec![MethodDef {
                name: "say_hello".into(),
                proto_name: "SayHello".into(),
                input_type: "super::HelloRequest".into(),
                output_type: "super::HelloReply".into(),
                client_streaming: false,
                server_streaming: false,
                codec_path: "grpc_codec_flatbuffers::FlatBuffersCodec".into(),
                comments: vec!["Sends a greeting.".to_string()],
            }],
        }
    }

    #[test]
    fn generates_parseable_dart_client() {
        let svc = sample_service();
        let code = generate(&svc, "super");
        assert!(code.contains("class GreeterClient"));
        assert!(code.contains("extends grpc.Client"));
        assert!(code.contains("say_hello"));
        assert!(code.contains("HelloRequest"));
        assert!(code.contains("HelloReply"));
    }

    #[test]
    fn generates_all_rpc_patterns() {
        let svc = ServiceDef {
            name: "TestSvc".into(),
            package: "test".into(),
            proto_name: "TestSvc".into(),
            comments: vec![],
            methods: vec![
                MethodDef {
                    name: "unary".into(),
                    proto_name: "Unary".into(),
                    input_type: "super::Req".into(),
                    output_type: "super::Resp".into(),
                    client_streaming: false,
                    server_streaming: false,
                    codec_path: "Codec".into(),
                    comments: vec![],
                },
                MethodDef {
                    name: "server_stream".into(),
                    proto_name: "ServerStream".into(),
                    input_type: "super::Req".into(),
                    output_type: "super::Resp".into(),
                    client_streaming: false,
                    server_streaming: true,
                    codec_path: "Codec".into(),
                    comments: vec![],
                },
                MethodDef {
                    name: "client_stream".into(),
                    proto_name: "ClientStream".into(),
                    input_type: "super::Req".into(),
                    output_type: "super::Resp".into(),
                    client_streaming: true,
                    server_streaming: false,
                    codec_path: "Codec".into(),
                    comments: vec![],
                },
                MethodDef {
                    name: "bidi".into(),
                    proto_name: "Bidi".into(),
                    input_type: "super::Req".into(),
                    output_type: "super::Resp".into(),
                    client_streaming: true,
                    server_streaming: true,
                    codec_path: "Codec".into(),
                    comments: vec![],
                },
            ],
        };

        let code = generate(&svc, "super");
        assert!(code.contains("Future<super.Resp> unary"));
        assert!(code.contains("ResponseStream<super.Resp> server_stream"));
        assert!(code.contains("Future<super.Resp> client_stream"));
        assert!(code.contains("ResponseStream<super.Resp> bidi"));
    }

    #[test]
    fn generates_client_method_descriptor() {
        let svc = sample_service();
        let code = generate(&svc, "super");
        assert!(code.contains("/helloworld.Greeter/SayHello"));
        assert!(code.contains("_serialize_HelloRequest"));
        assert!(code.contains("_deserialize_HelloReply"));
    }

    #[test]
    fn generates_create_factory_method() {
        let svc = sample_service();
        let code = generate(&svc, "super");
        assert!(code.contains("static Future<GreeterClient> create"));
        assert!(code.contains("required String host"));
        assert!(code.contains("required int port"));
        assert!(code.contains("grpc.ClientChannel("));
        assert!(code.contains("ChannelCredentials.insecure()"));
    }
}
