//! gRPC Server Reflection service implementation (v1).
//!
//! Enables tools like `grpcurl` to discover services without `.proto` files.
//!
//! # Usage
//!
//! ```ignore
//! use grpc_reflection::ReflectionServer;
//!
//! // FILE_DESCRIPTOR_SET is generated by protoc-rs at build time
//! let reflection = ReflectionServer::builder()
//!     .register_file_descriptor_set(proto::FILE_DESCRIPTOR_SET)
//!     .build();
//!
//! let router = Router::new()
//!     .add_service("grpc.reflection.v1.ServerReflection", reflection);
//! ```

pub mod proto;

use grpc_core::body::Body;
use grpc_core::codec::prost_codec::ProstCodec;
use grpc_core::{Request, Response, Status, Streaming};
use grpc_server::{Grpc, NamedService, StreamingService};
use std::collections::HashMap;
use std::convert::Infallible;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll};
use tokio_stream::Stream;

pub use proto::{
    server_reflection_response::MessageResponse, ErrorResponse, FileDescriptorResponse,
    ListServiceResponse, ServerReflectionRequest, ServerReflectionResponse, ServiceResponse,
};

type BoxFuture<T> = Pin<Box<dyn Future<Output = T> + Send + 'static>>;
type BoxStream<T> = Pin<Box<dyn Stream<Item = T> + Send + 'static>>;

/// State holding all indexed descriptors.
struct ReflectionState {
    service_names: Vec<String>,
    /// Map from symbol name (e.g., "helloworld.Greeter") to serialized FileDescriptorProto.
    symbols: HashMap<String, Vec<u8>>,
    /// Map from filename to serialized FileDescriptorProto.
    files: HashMap<String, Vec<u8>>,
}

/// Builder for creating a [`ReflectionServer`].
pub struct ReflectionServerBuilder {
    service_names: Vec<String>,
    symbols: HashMap<String, Vec<u8>>,
    files: HashMap<String, Vec<u8>>,
}

impl ReflectionServerBuilder {
    /// Register an encoded `FileDescriptorSet` (protobuf binary format).
    ///
    /// This is typically the output of `protoc --descriptor_set_out` or
    /// `protoc-rs-compiler`'s descriptor set serialization.
    pub fn register_encoded_file_descriptor_set(mut self, encoded: &[u8]) -> Self {
        use prost::Message;
        if let Ok(fds) = prost_types::FileDescriptorSet::decode(encoded) {
            for file in &fds.file {
                let file_bytes = {
                    let mut buf = Vec::new();
                    file.encode(&mut buf).ok();
                    buf
                };

                // Index by filename
                if let Some(name) = &file.name {
                    self.files.insert(name.clone(), file_bytes.clone());
                }

                let package = file.package.as_deref().unwrap_or("");

                // Index services
                for svc in &file.service {
                    if let Some(svc_name) = &svc.name {
                        let fqn = if package.is_empty() {
                            svc_name.clone()
                        } else {
                            format!("{package}.{svc_name}")
                        };
                        self.service_names.push(fqn.clone());
                        self.symbols.insert(fqn.clone(), file_bytes.clone());

                        // Index methods
                        for method in &svc.method {
                            if let Some(method_name) = &method.name {
                                let method_fqn = format!("{fqn}.{method_name}");
                                self.symbols.insert(method_fqn, file_bytes.clone());
                            }
                        }
                    }
                }

                // Index message types
                for msg in &file.message_type {
                    if let Some(msg_name) = &msg.name {
                        let fqn = if package.is_empty() {
                            msg_name.clone()
                        } else {
                            format!("{package}.{msg_name}")
                        };
                        self.symbols.insert(fqn, file_bytes.clone());
                    }
                }

                // Index enum types
                for enum_type in &file.enum_type {
                    if let Some(enum_name) = &enum_type.name {
                        let fqn = if package.is_empty() {
                            enum_name.clone()
                        } else {
                            format!("{package}.{enum_name}")
                        };
                        self.symbols.insert(fqn, file_bytes.clone());
                    }
                }
            }
        }
        self
    }

    /// Register a service name manually (for services without descriptors).
    pub fn register_service(mut self, name: impl Into<String>) -> Self {
        self.service_names.push(name.into());
        self
    }

    /// Build the [`ReflectionServer`].
    pub fn build(self) -> ReflectionServer {
        // Always include the reflection service itself
        let mut service_names = self.service_names;
        let reflection_name = ReflectionServer::NAME.to_string();
        if !service_names.contains(&reflection_name) {
            service_names.push(reflection_name);
        }

        ReflectionServer {
            state: Arc::new(ReflectionState {
                service_names,
                symbols: self.symbols,
                files: self.files,
            }),
        }
    }
}

/// gRPC Server Reflection service.
#[derive(Clone)]
pub struct ReflectionServer {
    state: Arc<ReflectionState>,
}

impl ReflectionServer {
    pub fn builder() -> ReflectionServerBuilder {
        ReflectionServerBuilder {
            service_names: Vec::new(),
            symbols: HashMap::new(),
            files: HashMap::new(),
        }
    }
}

impl NamedService for ReflectionServer {
    const NAME: &'static str = "grpc.reflection.v1.ServerReflection";
}

// --- Streaming handler ---

struct ReflectionInfoSvc {
    state: Arc<ReflectionState>,
}

impl StreamingService<ServerReflectionRequest> for ReflectionInfoSvc {
    type Response = ServerReflectionResponse;
    type ResponseStream = BoxStream<Result<ServerReflectionResponse, Status>>;
    type Future = BoxFuture<Result<Response<Self::ResponseStream>, Status>>;

    fn call(&mut self, request: Request<Streaming<ServerReflectionRequest>>) -> Self::Future {
        let state = self.state.clone();
        Box::pin(async move {
            let mut input = request.into_inner();
            let (tx, rx) = tokio::sync::mpsc::channel(32);

            tokio::spawn(async move {
                while let Some(Ok(req)) = input.message().await.transpose() {
                    let response = handle_reflection_request(&state, req);
                    if tx.send(Ok(response)).await.is_err() {
                        break;
                    }
                }
            });

            let stream = tokio_stream::wrappers::ReceiverStream::new(rx);
            Ok(Response::new(Box::pin(stream) as BoxStream<_>))
        })
    }
}

fn handle_reflection_request(
    state: &ReflectionState,
    req: ServerReflectionRequest,
) -> ServerReflectionResponse {
    use proto::server_reflection_request::MessageRequest;

    let original_request = req.clone();

    let response = match req.message_request {
        Some(MessageRequest::ListServices(_)) => {
            let services = state
                .service_names
                .iter()
                .map(|name| ServiceResponse { name: name.clone() })
                .collect();
            MessageResponse::ListServicesResponse(ListServiceResponse { service: services })
        }

        Some(MessageRequest::FileContainingSymbol(symbol)) => match state.symbols.get(&symbol) {
            Some(file_bytes) => MessageResponse::FileDescriptorResponse(FileDescriptorResponse {
                file_descriptor_proto: vec![file_bytes.clone()],
            }),
            None => MessageResponse::ErrorResponse(ErrorResponse {
                error_code: Status::not_found("").code() as i32,
                error_message: format!("symbol not found: {symbol}"),
            }),
        },

        Some(MessageRequest::FileByFilename(filename)) => match state.files.get(&filename) {
            Some(file_bytes) => MessageResponse::FileDescriptorResponse(FileDescriptorResponse {
                file_descriptor_proto: vec![file_bytes.clone()],
            }),
            None => MessageResponse::ErrorResponse(ErrorResponse {
                error_code: Status::not_found("").code() as i32,
                error_message: format!("file not found: {filename}"),
            }),
        },

        Some(MessageRequest::AllExtensionNumbersOfType(_)) => {
            // Return empty — extensions are rarely used
            MessageResponse::ErrorResponse(ErrorResponse {
                error_code: Status::unimplemented("").code() as i32,
                error_message: "extensions not supported".to_string(),
            })
        }

        _ => MessageResponse::ErrorResponse(ErrorResponse {
            error_code: Status::invalid_argument("").code() as i32,
            error_message: "unknown request type".to_string(),
        }),
    };

    ServerReflectionResponse {
        valid_host: String::new(),
        original_request: Some(original_request),
        message_response: Some(response),
    }
}

// --- tower::Service impl ---

impl tower_service::Service<http::Request<Body>> for ReflectionServer {
    type Response = http::Response<Body>;
    type Error = Infallible;
    type Future = BoxFuture<Result<http::Response<Body>, Infallible>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: http::Request<Body>) -> Self::Future {
        let state = self.state.clone();
        match req.uri().path() {
            "/grpc.reflection.v1.ServerReflection/ServerReflectionInfo" => Box::pin(async move {
                let mut grpc = Grpc::new(ProstCodec::<
                    ServerReflectionResponse,
                    ServerReflectionRequest,
                >::default());
                Ok(grpc.streaming(ReflectionInfoSvc { state }, req).await)
            }),
            _ => Box::pin(async { Ok(Status::unimplemented("").into_http()) }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builder_registers_service_names() {
        let server = ReflectionServer::builder()
            .register_service("helloworld.Greeter")
            .build();

        assert!(server
            .state
            .service_names
            .contains(&"helloworld.Greeter".to_string()));
        assert!(server
            .state
            .service_names
            .contains(&ReflectionServer::NAME.to_string()));
    }

    #[test]
    fn list_services_response() {
        let state = Arc::new(ReflectionState {
            service_names: vec!["test.Svc".into(), "test.Other".into()],
            symbols: HashMap::new(),
            files: HashMap::new(),
        });

        let req = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(
                proto::server_reflection_request::MessageRequest::ListServices(String::new()),
            ),
        };

        let resp = handle_reflection_request(&state, req);
        match resp.message_response {
            Some(MessageResponse::ListServicesResponse(list)) => {
                let names: Vec<_> = list.service.iter().map(|s| s.name.as_str()).collect();
                assert!(names.contains(&"test.Svc"));
                assert!(names.contains(&"test.Other"));
            }
            other => panic!("expected ListServicesResponse, got {other:?}"),
        }
    }

    #[test]
    fn symbol_not_found() {
        let state = Arc::new(ReflectionState {
            service_names: vec![],
            symbols: HashMap::new(),
            files: HashMap::new(),
        });

        let req = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(
                proto::server_reflection_request::MessageRequest::FileContainingSymbol(
                    "nonexistent.Service".into(),
                ),
            ),
        };

        let resp = handle_reflection_request(&state, req);
        match resp.message_response {
            Some(MessageResponse::ErrorResponse(err)) => {
                assert!(err.error_message.contains("not found"));
            }
            other => panic!("expected ErrorResponse, got {other:?}"),
        }
    }
}
